[project]
name = "ued"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
    "torch>=2.8.0",
]
